---
# tasks file for ansible-smartmontools

# variable configuration.
- name: include variables
  include_vars: main.yml

- fail: msg="variable '{{ item }}' not defined"
  when: item not in vars
  with_items: 
     - __smartd_email

- name: install smartmontools
  apt: name={{item}} state=present
  with_items:
    - smartmontools

- name: ffffffffffffffffffffffffff
  shell: pwd ; ls -lhatr ; ls -lahtr files/{{__smartd_basename}}
  args:
    warn: false

- name: copy smartd.conf
  shell: mv {{__smartd_cfg_file}} {{__smartd_bkup_cfg_file}} ; cp -p files/{{__smartd_basename}} {{__smartd_cfg_file}}
  args:
    warn: false
    creates: "{{__smartd_bkup_cfg_file}}"

- name: add email to configuration
  replace: dest={{__smartd_cfg_file}} regexp='\[\[notification_email\]\]' replace='{{__smartd_email}}' backup=yes
